build:
  cache:
    paths:
      - node_modules/
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - public
  only:
    - master

deploy:
  script:
    - ~/.yarn/bin/netlify deploy --prod --dir public
  only:
    - master
