build:
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - npm i
    - npm run build
  artifacts:
    paths:
      - public
  only:
    - master

deploy:
  stage: deploy
  script:
    - ~/.yarn/bin/netlify deploy --prod --dir public
  only:
    - master
