backend:
  name: gitlab
  repo: nils/blog-cms
  auth_type: implicit
  app_id: 2c368aa02d9067fb6ff2b0b01eb75f535df3572616ed99023c34b405fa5da955
  api_root: https://gitlab.strandrover.com/api/v4
  base_url: https://gitlab.strandrover.com
  auth_endpoint: oauth/authorize

media_folder: static/assets
public_folder: assets

collections:
  - name: post
    label: Post
    folder: src/posts
    create: true
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
